language: php

php:
  - 5.5
  - 5.6
  - 7

env:
  - LARAVEL_VERSION="5.1"
  - LARAVEL_VERSION="5.2"
  - LARAVEL_VERSION="5.3"

sudo: false

before_install:
  - phpenv config-rm xdebug.ini
  - composer require illuminate/database=${LARAVEL_VERSION}.*

install:
  - travis_retry composer install --no-interaction --prefer-dist

script:
  vendor/bin/phpunit
