language: php
sudo: false

php:
  - 5.5
  - 5.6
  - 7
  - 7.1

env:
  - LARAVEL_VERSION="5.1"
  - LARAVEL_VERSION="5.4"

matrix:
  exclude:
  - php: 5.5
    env: LARAVEL_VERSION="5.4"

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - phpenv config-rm xdebug.ini
  - composer require illuminate/database=${LARAVEL_VERSION}.*

install:
  - travis_retry composer install --no-interaction --prefer-dist

script:
  vendor/bin/phpunit
